import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import NavigationBar from "../components/NavigationBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoSanThai = Noto_Sans_Thai({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  preload: true,
  style: ['normal'],
  subsets: ['latin', 'latin-ext', 'thai'],
  display: "swap",
  variable: "--font-noto-sans-thai",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className="pt-[64px]"
      >
        <NavigationBar />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
